

BigWumpusIcon
;	db $B4,$B5,$B6,$B7
	db $C4,$C5,$C6,$C7
	db $D4,$D5,$D6,$D7
	db $E4,$E5,$E6,$E7

NumberTiles
digit0  db 0,1,16,17
digit1  db 2,3,18,19
digit2  db 4,5,20,21
digit3  db 6,7,22,23
digit4  db 8,9,24,25
digit5  db 10,11,26,27
digit6  db 12,13,28,29
digit7  db 14,15,30,31
digit8  db $D8,$D9,$E8,$E9
digit9  db $DA,$DB,$EA,$EB

PitPattern
	db $B0,$B1,$B2,$B3
	db $C0,$C1,$C2,$C3
	db $D0,$D1,$D2,$D3
	db $E0,$E1,$E2,$E3


PlayerIconPattern
	db $9d,$9e,$9f
	db $Ad,$Ae,$Af
	db $bd,$Be,$Bf
	db $Cd,$Ce,$Cf


Blanks
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	
TopTeeth1 ; copy 8 times
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	db  TOOTH1,SOLID_WHITE,SOLID_WHITE,TOOTH2
	
TopTeeth2 ; copy 8 times
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
	db  EMPTY,TOOTH1,TOOTH2,EMPTY
 
BottomTeeth1
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3
	db  TOOTH4,EMPTY,EMPTY,TOOTH3


BottomTeeth2
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 
	db  SOLID_WHITE,TOOTH4,TOOTH3,SOLID_WHITE 

Blanks2
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
	db EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY

;EyePattern
;	db $98,$99,$9A,$9B 
;	db $B8,$A9,$AA,$BB
;	db $B8,$B9,$BA,$BB
;	db $C8,$C9,$CA,$CB

ArrowSprites
	db $4C,$4B,$4C,$4B,$49,$4A,$49,$4A
	
;whether sprites should be flipped
ArrowSpriteFlags	
	db 3,3,FLIP_V.3,FLIP_V.3,FLIP_H.3,FLIP_H.3, 3, 3

ArrowXCoords ; for sprite 1 and 2
	db 124,124,124,124,248,240,0,8 ;up,dn,left,right 
	
ArrowYCoords ; for sprite 1 and 2
	db 224,216,8,16,128,128,128,128
    
ScoreBoardText
	db LTR_S,LTR_C,LTR_O,LTR_R,LTR_E,LTR_B,LTR_O,LTR_A,LTR_R,LTR_D,0

PrepareText
	db LTR_L,LTR_E,LTR_T,LTR_SPACE,LTR_T,LTR_H,LTR_E,LTR_SPACE,LTR_H,LTR_U,LTR_N,LTR_T,LTR_SPACE,LTR_B,LTR_E,LTR_G,LTR_I,LTR_N,LTR_EXCL,0

PlayAgainText
	db LTR_P,LTR_L,LTR_A,LTR_Y,LTR_SPACE,LTR_A,LTR_G,LTR_A,LTR_I,LTR_N,0

ShowMapText
	db LTR_S,LTR_H,LTR_O,LTR_W,LTR_SPACE,LTR_M,LTR_A,LTR_P,0


SelectDifficultyText
	db LTR_S,LTR_E,LTR_L,LTR_E,LTR_C,LTR_T,LTR_SPACE,LTR_S,LTR_K,LTR_I,LTR_L,LTR_L,LTR_SPACE,LTR_L,LTR_E,LTR_V,LTR_E,LTR_L,0

SetSkillText
	db LTR_S,LTR_E,LTR_T,LTR_SPACE,LTR_S,LTR_K,LTR_I,LTR_L,LTR_L,LTR_SPACE,LTR_L,LTR_E,LTR_V,LTR_E,LTR_L,0

TileText
  db LTR_E,LTR_V,LTR_A,LTR_N,LTR_SPACE,LTR_C,LTR_SPACE,LTR_W,LTR_R,LTR_I,LTR_G,LTR_H,LTR_T,0    

HuntWumpusText
	db LTR_H,LTR_U,LTR_N,LTR_T,LTR_SPACE,LTR_A,LTR_G,LTR_A,LTR_I,LTR_N,0

EasyText
	db LTR_E, LTR_A,LTR_S, LTR_Y, LTR_SPACE,LTR_P,LTR_A,LTR_S,LTR_S,LTR_A,LTR_G,LTR_E,LTR_S,0         

TwistyText
	db LTR_T, LTR_W,LTR_I, LTR_S, LTR_T, LTR_Y, LTR_SPACE,LTR_P,LTR_A,LTR_S,LTR_S,LTR_A,LTR_G,LTR_E,LTR_S,0         


VeryTwistyText
	db LTR_V,LTR_E,LTR_R,LTR_Y,LTR_SPACE,LTR_T, LTR_W,LTR_I, LTR_S, LTR_T, LTR_Y, LTR_SPACE,LTR_P,LTR_A,LTR_S,LTR_S,LTR_A,LTR_G,LTR_E,LTR_S,0         

NeedHelpText
	db LTR_W,LTR_A,LTR_I,LTR_T,LTR_EXCL,LTR_SPACE, LTR_I,LTR_SPACE, LTR_N, LTR_E, LTR_E, LTR_D,LTR_SPACE,LTR_H,LTR_E,LTR_L,LTR_P,LTR_EXCL,0         


VictoryTextSpr
  db SPR_V,SPR_I,SPR_C,SPR_T,SPR_O,SPR_R,SPR_Y,SPR_EXCL,0 

PitTextSpr
  db SPR_P,SPR_I,SPR_T,SPR_EXCL,0 

;EasyTextSpr
;  db SPR_E,SPR_A,SPR_S,SPR_Y,0 

;NormalTextSpr
 ; db SPR_N,SPR_O,SPR_R,SPR_M,SPR_A,SPR_L,0 

;TwistyTextSpr
;   db SPR_T,SPR_W,SPR_I,SPR_S,SPR_T,SPR_Y,0 



DeadWumpusSprites
	db $8a,$8b,$8c,$8d	
	db $9a,$9b,$9c,$9d	
	db $Aa,$Ab,$Ac,$Ad	


DeadWumpusXCoords 
	db 112,120,128,136	
	db 112,120,128,136
	db 112,120,128,136

DeadWumpusYCoords 
	db 128,128,128,128	
	db 136,136,136,136
	db 144,144,144,144

DeathScreenData

	db $FF,$DC,$08,$DC,$01,$98,$01,$99,$01,$9A,$01,$9B,$0A,$DC,$01,$98,$02,$DD,$01,$9B,$0E,$DC,$01,$B8
	db $01,$A9,$01,$AA,$01,$BB,$0A,$DC,$01,$A8,$01,$A9,$01,$AA,$01,$DD,$0E,$DC,$01,$B8,$01,$B9,$01,$BA
	db $01,$BB,$0A,$DC,$01,$DD,$01,$B9,$01,$BA,$01,$DD,$0E,$DC,$01,$C8,$01,$C9,$01,$CA,$01,$CB,$0A,$DC
	db $01,$C8,$01,$C9,$01,$CA,$01,$CB,$30,$DC,$01,$C1,$FF,$DC,$FF,$DC,$18,$DC,$00