;locatations of letter tiles withing the chr ROM
;this will be project specific
LTR_A equ $20
LTR_B equ $21
LTR_C equ $22
LTR_D equ $23
LTR_E equ $24
LTR_F equ $25
LTR_G equ $26
LTR_H equ $27
LTR_I equ $28
LTR_J equ $29
LTR_K equ $2A
LTR_L equ $2B
LTR_M equ $2C
LTR_N equ $2D
LTR_O equ $2E
LTR_P equ $2F
LTR_Q equ $F0
LTR_R equ $F1
LTR_S equ $F2
LTR_T equ $F3
LTR_U equ $F4
LTR_V equ $F5
LTR_W equ $F6
LTR_X equ $f7
LTR_Y equ $f8
LTR_Z equ $f9
LTR_EXCL equ $fA
LTR_SPACE equ $DC

SPR_A equ $CA
SPR_B equ $CB
SPR_C equ $CC
SPR_D equ $CD
SPR_E equ $CE
SPR_F equ $CF
SPR_G equ $D0
SPR_H equ $D1
SPR_I equ $D2
SPR_J equ $D3
SPR_K equ $D4
SPR_L equ $D5
SPR_M equ $D6
SPR_N equ $D7
SPR_O equ $D8
SPR_P equ $D9
SPR_Q equ $DA
SPR_R equ $DB
SPR_S equ $DC
SPR_T equ $DD
SPR_U equ $DE
SPR_V equ $DF
SPR_W equ $E0
SPR_X equ $E1
SPR_Y equ $E2
SPR_Z equ $E3
SPR_EXCL equ $E4
SPR_SPACE equ $0f