;titlemusic.asm
TitleMusicTreble
  db B2,EIGHTH_NOTE,CS3,EIGHTH_NOTE,D3,EIGHTH_NOTE,E3,EIGHTH_NOTE,FS3,EIGHTH_NOTE,D3,EIGHTH_NOTE,FS3,QUARTER_NOTE
  db F3,EIGHTH_NOTE,CS3,EIGHTH_NOTE,F3,QUARTER_NOTE,E3,EIGHTH_NOTE,C3,EIGHTH_NOTE,E3,QUARTER_NOTE
  db B2,EIGHTH_NOTE,CS3,EIGHTH_NOTE,D3,EIGHTH_NOTE,E3,EIGHTH_NOTE,FS3,EIGHTH_NOTE,D3,EIGHTH_NOTE,FS3,EIGHTH_NOTE
  db B3,EIGHTH_NOTE,A3,EIGHTH_NOTE,FS3,EIGHTH_NOTE,D3,EIGHTH_NOTE,FS3,EIGHTH_NOTE,A3,HALF_NOTE
  db STOP_MUSIC


TitleMusicBass
  db B2,QUARTER_NOTE,FS3,QUARTER_NOTE,B2,QUARTER_NOTE,FS3,QUARTER_NOTE
  db B2,QUARTER_NOTE,FS3,QUARTER_NOTE,B2,QUARTER_NOTE,FS3,QUARTER_NOTE
  db B2,QUARTER_NOTE,FS3,QUARTER_NOTE,B2,QUARTER_NOTE,FS3,QUARTER_NOTE
  db D3,QUARTER_NOTE,A2,QUARTER_NOTE,D3,QUARTER_NOTE,D3,QUARTER_NOTE
  db STOP_MUSIC
  