VictoryMusic 
  db G4, EIGHTH_NOTE, REST, G4, EIGHTH_NOTE, REST, E4, EIGHTH_NOTE, REST
  db G4, EIGHTH_NOTE, REST, G4, EIGHTH_NOTE, REST, E4, EIGHTH_NOTE, REST
  db G4, EIGHTH_NOTE, REST, G4, QUARTER_NOTE, REST, C5, HALF_NOTE, REST
  db G4, EIGHTH_NOTE, REST, G4, QUARTER_NOTE, REST, G4, EIGHTH_NOTE, REST
  db E4, QUARTER_NOTE, REST, E4, EIGHTH_NOTE, REST, C4,  HALF_NOTE, STOP_MUSIC


VictoryMusicBass 
  db E3, EIGHTH_NOTE, REST, C3, EIGHTH_NOTE, REST, C3, EIGHTH_NOTE, REST
  db E3, EIGHTH_NOTE, REST, C3, EIGHTH_NOTE, REST, C3, EIGHTH_NOTE, REST
  db C3, EIGHTH_NOTE, REST, C3, QUARTER_NOTE, REST, E4, HALF_NOTE, REST
  db E3, EIGHTH_NOTE, REST, C3, QUARTER_NOTE, REST, C3, EIGHTH_NOTE, REST
  db C3, QUARTER_NOTE, REST, C3, EIGHTH_NOTE, REST, E3,  HALF_NOTE, STOP_MUSIC

LevelStartMusic
  db F3,EIGHTH_NOTE,AS3,EIGHTH_NOTE,D4,EIGHTH_NOTE
  db F3,EIGHTH_NOTE,AS3,EIGHTH_NOTE,D4,EIGHTH_NOTE
  db F3,EIGHTH_NOTE,AS3,EIGHTH_NOTE,D4,EIGHTH_NOTE
  db STOP_MUSIC

ErrorBeep
  db C3, SIXTEENTH_NOTE, STOP_MUSIC

  