;wumpusdefs.h
UP equ 0 ; 
DOWN EQU 1
LEFT EQU 2
RIGHT EQU 3
BLANK_TILE equ $64
SOLID_BLACK equ $34
EMPTY equ $64
TOOTH1 equ $88
TOOTH2 equ $89
TOOTH3 equ $7A
TOOTH4 equ $7B
SOLID_TILE equ $dc
WHITE_TILE equ $79
SOLID_WHITE equ $79
; BLANK_TILE equ $64
; SOLID_BLACK equ $34
; EMPTY equ $64
BAT_SPRITE1 equ  $4D
BAT_SPRITE2 equ  $4E
 
FLIP_H equ $40
FLIP_V equ $80
BOW_TILE equ $6C

TICKS_PER_ARROW_MOVE equ 1
BAT_ICON equ $88
; P1_CONTROLLER equ $4016
PLAYER_SCORE equ $21A8 
PIT_SCORE equ $21AF  
WUMPUS_SCORE equ $21B6
WUMPUS_ICON_ADDR equ $2136
PIT_ICON_ADDR equ $210f  
PLAYER_ICON_ADDR equ $2109  
SCOREBOARD_TEXT_ADDR equ $20AC
PREPARE_TEXT_ADDR equ $20C7
;PLAY_AGAIN_TEXT_ADDR equ $2230
PLAY_AGAIN_TEXT_ADDR equ $222F
;REVEAL_BOARD_TEXT_ADDR equ $2290
REVEAL_BOARD_TEXT_ADDR equ $228f

CHANGE_DIFFICULTY_TEXT_ADDR equ $22ef
EASY_TEXT_ADDR equ $21AA
TWISTY_TEXT_ADDR equ $220A
VERY_TWISTY_TEXT_ADDR equ $226A
HELP_TEXT_ADDR equ $22CA
SELECT_TEXT_ADDR equ $2148
DEAD_WUMPUS_ADDR equ $220f
VICTORY_TEXT_ADDR equ $218D

CURSOR_PLAY_AGAIN_Y equ 134 
CURSOR_SKILL_LEVEL_Y equ 158
PLAY_AGAIN_OPTION equ 0 
SKILL_LEVEL_OPTION equ 1 
CURSOR_TILE equ $89

;title
WUMPUS_EYES_TOP equ 64

PPU_ATTRS equ $23C0

BUTTON_A equ 128
BUTTON_B equ 64
BUTTON_SELECT equ 32
BUTTON_START equ 16
BUTTON_UP equ 8
BUTTON_DOWN equ 4
BUTTON_LEFT equ 2
BUTTON_RIGHT equ 1

EASY equ $0
MEDIUM equ $1
HARD equ $2