TriforceGlowTimer EQU $412
InitializedWaterfallAnimation EQU $41F
TitleWaveYs EQU $420
DemoPhase EQU $42C
DemoPhase0Subphase1Cycle EQU $437
DemoItemIds EQU $444

CharBoardIndex EQU $41F
InitializedNameField EQU $420
NameCharOffset EQU $421
NameInputCharBuf EQU $422

EndingFlashLongTimer EQU $4D
PeaceCharDelayCounter EQU $412
PeaceCharIndex EQU $413
TextboxCharIndex EQU $416
TextboxCharPtr EQU $45F
