ObjWantsToShoot EQU $412
ObjTurnRate EQU $41F
ObjTurnTimer EQU $478

ObjRemDistance EQU $394

ObjPushTimer EQU $412

ObjAngleFrac EQU $380
ObjAngleWhole EQU $394

Shot_ObjBounceDir EQU $380
Shot_ObjBounceDist EQU $394

TileObjRoomId EQU $412

Fireball_ObjPosFracX EQU $451
Fireball_ObjPosFracY EQU $45E
Fireball_ObjDirToTargetX EQU $412
Fireball_ObjDirToTargetY EQU $437
Fireball_ObjQSpeedX EQU $41F
Fireball_ObjQSpeedY EQU $444

Flyer_ObjSpeedFrac EQU $412
Flyer_ObjSpeed EQU $41F
Flyer_ObjTurns EQU $42C
Flyer_ObjDistTraveled EQU $437
Flyer_ObjFlyingState EQU $444
Flyer_ObjOffsetX EQU $46B
Flyer_ObjOffsetY EQU $478

Statue_ObjFireballTimer EQU $4E8

Jumper_ObjSpeedWholeY EQU $412
Jumper_ObjSpeedFracY EQU $41F
Jumper_ObjTargetY EQU $444
Jumper_ObjReversalCount EQU $451

Wallmaster_ObjStep EQU $412
Wallmaster_ObjTilesCrossed EQU $41F

Moldorm_ObjBounceDir EQU $3BC
Moldorm_ObjOldDir EQU $380

Digdogger_ObjSpeedFrac EQU $41F
Digdogger_ObjSpeedWhole EQU $42C
Digdogger_ObjTargetSpeedFrac EQU $437
Digdogger_ObjTargetSpeedWhole EQU $444
Digdogger_ObjSpeedFlag EQU $45E
Digdogger_ObjIsChild EQU $46B
Digdogger_ObjCurPart EQU $478

Aquamentus_ObjFireballOffset EQU $478

Dodongo_ObjBloatedSubstate EQU $42C
Dodongo_ObjBombHits EQU $437
Dodongo_ObjBloatedTimer EQU $45E

PolsVoice_ObjSpeedWhole EQU $412
PolsVoice_ObjLastTile EQU $41F
PolsVoice_ObjTargetY EQU $42C
PolsVoice_ObjSpeedFrac EQU $444

Wizzrobe_ObjLastTile EQU $41F

BlueWizzrobe_ObjTurnCounter EQU $412

RedWizzrobe_ObjFadeCounter EQU $394
RedWizzrobe_ObjAnimCounter EQU $412

Manhandla_ObjSpeedAccum EQU $412
Manhandla_ObjSpeedFrac EQU $41F
Manhandla_ObjSpeedWhole EQU $42C
Manhandla_ObjPrevFrame EQU $437
Manhandla_ObjFrameAccum EQU $451
Manhandla_ObjFrame EQU $478

Manhandla_SegmentJustDied EQU $383
Manhandla_BounceDir EQU $385

Gohma_ObjShootTimer EQU $380
Gohma_ObjDistTraveled EQU $412
Gohma_ObjMoveAccum EQU $41F
Gohma_ObjNextOpenEyeCounter EQU $42C
Gohma_ObjEyeOpenTimer EQU $444
Gohma_ObjGoStraight EQU $451
Gohma_ObjSprints EQU $45E
Gohma_ObjEyeState EQU $46B
Gohma_ObjEyeAnimCounter EQU $478

Lamnola_Type EQU $4E7
Lamnola_Speed EQU $4E6

Patra_ObjManeuverIndex EQU $45E

Ganon_ScenePhase EQU $445

Ganon_ObjAnimationFrame EQU $46B
Ganon_ObjPhase EQU $42C
Ganon_ObjCloudDist EQU $478

Gleeok_NeckXs0 EQU $438
Gleeok_NeckXs1 EQU $452
Gleeok_NeckXs2 EQU $46C
Gleeok_NeckXs3 EQU $395

Gleeok_NeckYs0 EQU $445
Gleeok_NeckYs1 EQU $45F
Gleeok_NeckYs2 EQU $479
Gleeok_NeckYs3 EQU $3BD

Gleook_HeadInfo0 EQU $420
Gleook_HeadInfo1 EQU $42D
Gleook_HeadInfo2 EQU $381
Gleook_HeadInfo3 EQU $3A9

Gleeok_ObjHeadInfo EQU $413
Gleeok_ObjHeadDirCounterH EQU $413
Gleeok_ObjHeadDirCounterV EQU $414
Gleeok_ObjHeadSpeedX EQU $415
Gleeok_ObjHeadSpeedY EQU $416
Gleeok_ObjHeadDirChangeCounter EQU $417
Gleeok_ObjHeadDelay EQU $418

Gleeok_WrithingCounter EQU $510

GLEEOK_DIRCOUNTERH EQU 0
GLEEOK_DIRCOUNTERV EQU 1
GLEEOK_SPEEDX EQU 2
GLEEOK_SPEEDY EQU 3
GLEEOK_DIRCHANGECOUNTER EQU 4
GLEEOK_DELAY EQU 5
