; Warnings from generation:
; WARNING: skipping "init": no palette file (src\games\zelda\palettes\init.txt)

; Auto-generated by scripts/generate-palette-transitions.js from src/games/zelda/palettes/transitions.txt.
; Do not edit by hand -- regenerate instead.
;
; Requires (already implemented, see src/rom/rom_color.s):
;   NES_ColorToIIgs -- A = NES color index -> A = IIgs 12-bit RGB
; Targets IIgs palette 0 (SHR_PALETTES, see src/core/Defs.s).

; Palette ids (first appearance order in the transitions file). Ids are
; word-aligned so they can be used directly as a PAL_ADDRS byte offset.
PAL_TITLE_SCREEN equ 2
PAL_INTRO equ 4
PAL_SELECT_SCREEN equ 6
PAL_OVERWORLD equ 8
PAL_CAVE equ 10

            mx    %00

; UpdatePalette
; X = from palette id (PAL_*), Y = to palette id (PAL_*)
; Loads all 16 IIgs CLUT slots of palette 0 from the target palette's table,
; then tail-calls RefreshPPUAttributes with the from->to BG0-BG3 redraw bitmap.
UpdatePalette
            lda   BG_UPDATE_MASKS,x
            pha
            lda   (1,s),y
            sta   1,s               ; stash the redraw mask, safe from X/Y reuse below
            lda   PAL_ADDRS,y
            pha
            ldy   #0
:loop       lda   (1,s),y
            jsr   NES_ColorToIIgs
            tyx
            stal  SHR_PALETTES,x
            iny
            iny
            cpy   #32      ; 16 slots, 2 bytes/slot
            bcc   :loop
            pla                     ; discard the color table pointer
            pla                     ; A = redraw mask
            jmp   RefreshPPUAttributes  ; tail call

; DetectNESPalette
; Identifies the currently active NES palette from 1 byte of NES palette RAM ($3F00-$3F1F) -- the
; minimum needed to tell every known palette apart (see scripts/generate-palette-transitions.js).
; Returns A = Y = PAL_* id, or 0 if the current palette RAM matches no known palette.
; Y is left holding the id so it can be passed straight through as UpdatePalette's "to".
            mx    %10
DetectNESPalette
            php
            sep   #$20
            ldal  PPU_MEM+$3F09
            cmp   #$08
            bne   :try_intro
            ldy   #PAL_TITLE_SCREEN
            bra   :found
:try_intro
            cmp   #$16
            bne   :try_select_screen
            ldy   #PAL_INTRO
            bra   :found
:try_select_screen
            cmp   #$0C
            bne   :try_overworld
            ldy   #PAL_SELECT_SCREEN
            bra   :found
:try_overworld
            cmp   #$1A
            bne   :try_cave
            ldy   #PAL_OVERWORLD
            bra   :found
:try_cave
            cmp   #$30
            bne   :notfound
            ldy   #PAL_CAVE
            bra   :found
:notfound
            ldy   #0
:found
            plp
            tya
            rts

            mx    %00

; id -> palette color table address. Entry 0 is unused (no palette has id 0).
PAL_ADDRS
            dw    $0000
            dw    PAL_TITLE_SCREEN_TABLE
            dw    PAL_INTRO_TABLE
            dw    PAL_SELECT_SCREEN_TABLE
            dw    PAL_OVERWORLD_TABLE
            dw    PAL_CAVE_TABLE

; from-id -> that palette's BG_UPDATE_MASKS_<name> row. Entry 0 is unused.
BG_UPDATE_MASKS
            dw    $0000
            dw    BG_UPDATE_MASKS_TITLE_SCREEN
            dw    BG_UPDATE_MASKS_INTRO
            dw    BG_UPDATE_MASKS_SELECT_SCREEN
            dw    BG_UPDATE_MASKS_OVERWORLD
            dw    BG_UPDATE_MASKS_CAVE

; title_screen
PAL_TITLE_SCREEN_TABLE
            dw    $36,$0F,$00,$10,$17,$07,$08,$1A,$28,$30,$3B,$22,$16,$27,$00,$00

; intro
PAL_INTRO_TABLE
            dw    $0F,$30,$21,$16,$29,$1A,$09,$37,$17,$02,$22,$27,$0B,$1B,$2B,$00

; select_screen
PAL_SELECT_SCREEN_TABLE
            dw    $0F,$30,$00,$12,$16,$27,$36,$0C,$1C,$2C,$29,$07,$15,$00,$00,$00

; overworld
PAL_OVERWORLD_TABLE
            dw    $0F,$30,$00,$12,$16,$27,$36,$1A,$37,$17,$29,$02,$22,$1C,$00,$00

; cave
PAL_CAVE_TABLE
            dw    $0F,$30,$00,$12,$16,$27,$36,$07,$17,$29,$02,$22,$1C,$00,$00,$00

; BG0-BG3 redraw bitmap for each from -> to move (bit0=BG0 .. bit3=BG3).
; Entry 0 in each row is unused; a from -> from move is always $0000.
; from title_screen
BG_UPDATE_MASKS_TITLE_SCREEN
            dw    $0000
            dw    %0000_0000   ; to title_screen
            dw    %0000_0101   ; to intro
            dw    %0000_0000   ; to select_screen
            dw    %0000_1000   ; to overworld
            dw    %0000_0001   ; to cave

; from intro
BG_UPDATE_MASKS_INTRO
            dw    $0000
            dw    %0000_0101   ; to title_screen
            dw    %0000_0000   ; to intro
            dw    %0000_0101   ; to select_screen
            dw    %0000_0101   ; to overworld
            dw    %0000_0101   ; to cave

; from select_screen
BG_UPDATE_MASKS_SELECT_SCREEN
            dw    $0000
            dw    %0000_0000   ; to title_screen
            dw    %0000_0101   ; to intro
            dw    %0000_0000   ; to select_screen
            dw    %0000_0000   ; to overworld
            dw    %0000_0100   ; to cave

; from overworld
BG_UPDATE_MASKS_OVERWORLD
            dw    $0000
            dw    %0000_1000   ; to title_screen
            dw    %0000_0101   ; to intro
            dw    %0000_0000   ; to select_screen
            dw    %0000_0000   ; to overworld
            dw    %0000_0000   ; to cave

; from cave
BG_UPDATE_MASKS_CAVE
            dw    $0000
            dw    %0000_0001   ; to title_screen
            dw    %0000_0101   ; to intro
            dw    %0000_0100   ; to select_screen
            dw    %0000_0000   ; to overworld
            dw    %0000_0000   ; to cave

