; Auto-generated by scripts/generate-palette-transitions.js from src/games/zelda/palettes/.
; Do not edit by hand -- regenerate instead.
;
; Every palette has one fixed IIgs slot layout: the IIgs palette 0 slot that each of the 32 NES
; palette RAM entries ($3F00-$3F1F) is shown in.  The layouts are chosen together, so that the
; background groups that keep the same slots across the transitions don't need their tiles
; redrawn (a group whose slots change has to be recompiled with the new swizzle table).
;
; Requires: NES_ColorToIIgs_X, NES_SetPaletteMap, RefreshPPUAttributes, PPU_MEM, SHR_PALETTES

; Swizzle tables, in the PALDATA segment (palettes.s)
PAL_TITLE_SCREEN_SWIZZLE EXT
PAL_INTRO_SWIZZLE EXT
PAL_SELECT_SCREEN_SWIZZLE EXT
PAL_OVERWORLD_SWIZZLE EXT
PAL_CAVE_SWIZZLE EXT
PAL_DUNGEON1_SWIZZLE EXT
PAL_DUNGEON2_SWIZZLE EXT
PAL_DUNGEON3_SWIZZLE EXT
PAL_DUNGEON4_SWIZZLE EXT
PAL_DUNGEON5_SWIZZLE EXT
PAL_DUNGEON6_SWIZZLE EXT
PAL_DUNGEON7_SWIZZLE EXT
PAL_DUNGEON8_SWIZZLE EXT
PAL_DUNGEON9_SWIZZLE EXT

; Palette ids, word-aligned so they index the tables below directly.  0 = no palette.
PAL_TITLE_SCREEN equ 2
PAL_INTRO equ 4
PAL_SELECT_SCREEN equ 6
PAL_OVERWORLD equ 8
PAL_CAVE equ 10
PAL_DUNGEON1 equ 12
PAL_DUNGEON2 equ 14
PAL_DUNGEON3 equ 16
PAL_DUNGEON4 equ 18
PAL_DUNGEON5 equ 20
PAL_DUNGEON6 equ 22
PAL_DUNGEON7 equ 24
PAL_DUNGEON8 equ 26
PAL_DUNGEON9 equ 28

; Layouts (NES color -> [slots] per group; *reserved, ~shown as):
;   title_screen
;     BG0 $36 $0F $00 $10 -> [0,6,1,2]
;     BG1 $36 $17 *$07 $0F -> [0,4,5,6]
;     BG2 $36 $08 $1A $28 -> [0,7,10,11]
;     BG3 $36 $30 $3B $22 -> [0,3,8,9]
;     SP0 $36 $30 $3B $16 -> [0,3,8,12]
;     SP1 $36 $17 $27 $0F -> [0,4,13,6]
;     SP2 $36 $08 $1A $28 -> [0,7,10,11]
;     SP3 $36 $30 $3B $22 -> [0,3,8,9]
;   intro
;     BG0 $0F $30 $30 $30 -> [0,5,5,5]
;     BG1 $0F $21 $30 $30 -> [0,4,5,6]
;     BG2 $0F $16 $30 $30 -> [0,1,5,5]
;     BG3 $0F $29 $1A $09 -> [0,3,8,9]
;     SP0 $0F $29 $37 $17 -> [0,3,2,7]
;     SP1 $0F $02 $22 $30 -> [0,10,11,5]
;     SP2 $0F $16 $27 $30 -> [0,1,12,5]
;     SP3 $0F $0B $1B $2B -> [0,13,14,15]
;   select_screen
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0C $1C $2C -> [0,7,8,9]
;     BG3 $0F $12 $1C $2C -> [0,3,8,9]
;     SP0 $0F *$29 $27 $07 -> [0,10,5,11]
;     SP1 $0F *$29 $27 $07 -> [0,12,5,11]
;     SP2 $0F *$29 $27 $07 -> [0,13,5,11]
;     SP3 $0F *$15 $27 $30 -> [0,14,5,1]
;   overworld
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $1A $37 $12 -> [0,7,8,3]
;     BG3 $0F $17 $37 $12 -> [0,13,8,3]
;     SP0 $0F *$29 $27 $17 -> [0,10,5,13]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$1C *$16 -> [0,9,14,15]
;   cave
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $30 $00 $12 -> [0,1,2,3]
;     BG3 $0F $07 $0F $17 -> [0,7,0,13]
;     SP0 $0F *$29 $27 $17 -> [0,10,5,13]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$1C *$16 -> [0,8,9,14]
;   dungeon1
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0C $1C $2C -> [0,7,8,9]
;     BG3 $0F $12 $1C $2C -> [0,3,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0C *$1C *$2C -> [0,13,14,15]
;   dungeon2
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $02 $12 $22 -> [0,11,3,12]
;     BG3 $0F $16 $12 $22 -> [0,4,3,12]
;     SP0 $0F *$29 $27 $17 -> [0,10,5,13]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$02 *$12 *$22 -> [0,7,8,9]
;   dungeon3
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0B $1B $2B -> [0,7,8,9]
;     BG3 $0F $16 $1B $2B -> [0,4,8,9]
;     SP0 $0F *$29 $37~$36 $17~$16 -> [0,10,6,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0B *$1B *$2B -> [0,13,14,15]
;   dungeon4
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $08 $18 $28 -> [0,7,8,9]
;     BG3 $0F $12 $18 $28 -> [0,3,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$18 *$28 -> [0,13,14,15]
;   dungeon5
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0A $1A $2A -> [0,7,8,9]
;     BG3 $0F $16 $1A $2A -> [0,4,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0A *$1A *$2A -> [0,13,14,15]
;   dungeon6
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $08 $18 $28 -> [0,7,8,9]
;     BG3 $0F $16 $18 $28 -> [0,4,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$08 *$18 *$28 -> [0,13,14,15]
;   dungeon7
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0A $1A $2A -> [0,7,8,9]
;     BG3 $0F $12 $1A $2A -> [0,3,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0A *$1A *$2A -> [0,13,14,15]
;   dungeon8
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $00 $10 $30 -> [0,2,7,1]
;     BG3 $0F $22 $10 $30 -> [0,12,7,1]
;     SP0 $0F *$29 $27 $17 -> [0,10,5,13]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$00 *$10 *$30 -> [0,8,9,14]
;   dungeon9
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $00 $10 $30 -> [0,2,7,1]
;     BG3 $0F $16 $10 $30 -> [0,4,7,1]
;     SP0 $0F *$29 $27 $17 -> [0,10,5,13]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$10 *$30 -> [0,8,9,14]

            mx    %00

; UpdatePalette
;
; X = from palette id (PAL_*, or 0 for none), Y = to palette id
;
; Switches the swizzle tables to the new palette, loads its colors (LoadPaletteColors), then redraws
; the background groups whose slots changed.  Call from the GS task (it redraws tiles).
UpdatePalette
            lda   BG_UPDATE_MASKS,x
            pha
            lda   (1,s),y
            sta   1,s                 ; 1,s = groups to redraw

            phy
            ldx   PAL_SWIZZLE_LO,y
            lda   PAL_SWIZZLE_HI,y
            jsr   NES_SetPaletteMap
            ply

            jsr   LoadPaletteColors
            pla
            jmp   RefreshPPUAttributes

; LoadPaletteColors
;
; Y = palette id.  Loads IIgs palette 0 from the current NES palette RAM, in the palette's layout,
; so the colors the game changes on the fly (fades, color cycling, ...) are shown too.  Slot 0 (the
; universal background color) is left alone: the game's $3F00 writes set it directly.
LoadPaletteColors
            lda   PAL_CELLS,y
            pha                       ; 1,s = slot map
            ldy   #31                 ; Backwards, so the BG colors win a shared slot
:loop       lda   (1,s),y
            and   #$00FF
            cmp   #$00FF
            beq   :next               ; not shown
            pha                       ; 1,s = slot * 2
            tyx
            ldal  PPU_MEM+$3F00,x
            jsr   NES_ColorToIIgs_X
            plx
            stal  SHR_PALETTES,x
:next       dey
            bpl   :loop
            pla
            rts

; DetectNESPalette
;
; X = the current palette id (0 = none).  Returns A = Y = the PAL_* id of the palette whose
; colors 1-3 are all in palette RAM (other than the reserved ones), or 0 if there is none (e.g. a
; step of a fade).  The current palette is tried first,
; then the palettes that follow it in the transitions, then the rest.
DetectNESPalette
            php
            rep   #$30
            stx   :from
            txa
            beq   :all
            jsr   :match              ; still the current palette?
            bcs   :found
            ldx   :from
            lda   PAL_SUCC,x          ; its successors, a 0-terminated list of ids
:snext      sta   :ptr
            tax
            lda:  0,x
            beq   :all
            tax
            jsr   :match
            bcs   :found
            lda   :ptr
            inc
            inc
            bra   :snext
:all        ldx   #2
:anext      jsr   :match
            bcs   :found
            inx
            inx
            cpx   #30
            bcc   :anext
            ldx   #0
:found      txy
            plp
            tya
            rts

; X = palette id.  Carry set if its colors are in palette RAM.  X is kept.  Only colors 1-3 of
; each group are compared (24 at most): color 0 is always IIgs slot 0.  One pass per group, from
; SP3 back to BG0, with its three colors compared inline.  NES colors are $00-$3F, so the $FF of a
; reserved color is the only table byte with bit 7 set, and bmi skips it.
:match      phx
            lda   PAL_MATCH,x
            clc
            adc   #21
            tay                       ; Y -> the last group's 3 bytes
            ldx   #28                 ; X = the last group's palette RAM offset
            sep   #$20
            mx    %10
:group      lda:  0,y                 ; color 1
            bmi   *+8                 ; $FF = any value
            cmpl  PPU_MEM+$3F01,x
            bne   :mfail
            lda:  1,y                 ; color 2
            bmi   *+8
            cmpl  PPU_MEM+$3F02,x
            bne   :mfail
            lda:  2,y                 ; color 3
            bmi   *+8
            cmpl  PPU_MEM+$3F03,x
            bne   :mfail
            dey
            dey
            dey
            dex
            dex
            dex
            dex
            bpl   :group
            rep   #$20
            mx    %00
            plx
            sec
            rts
:mfail      rep   #$20
            plx
            clc
            rts

:from       ds    2
:ptr        ds    2

; id -> colors 1-3 of each group to match (BG0-BG3, SP0-SP3; $FF = any value: reserved)
PAL_MATCH
            dw    0
            dw    PAL_TITLE_SCREEN_MATCH
            dw    PAL_INTRO_MATCH
            dw    PAL_SELECT_SCREEN_MATCH
            dw    PAL_OVERWORLD_MATCH
            dw    PAL_CAVE_MATCH
            dw    PAL_DUNGEON1_MATCH
            dw    PAL_DUNGEON2_MATCH
            dw    PAL_DUNGEON3_MATCH
            dw    PAL_DUNGEON4_MATCH
            dw    PAL_DUNGEON5_MATCH
            dw    PAL_DUNGEON6_MATCH
            dw    PAL_DUNGEON7_MATCH
            dw    PAL_DUNGEON8_MATCH
            dw    PAL_DUNGEON9_MATCH
PAL_TITLE_SCREEN_MATCH
            db    $0F,$00,$10,$17,$FF,$0F,$08,$1A,$28,$30,$3B,$22   ; BG0-BG3
            db    $30,$3B,$16,$17,$27,$0F,$08,$1A,$28,$30,$3B,$22   ; SP0-SP3
PAL_INTRO_MATCH
            db    $30,$30,$30,$21,$30,$30,$16,$30,$30,$29,$1A,$09   ; BG0-BG3
            db    $29,$37,$17,$02,$22,$30,$16,$27,$30,$0B,$1B,$2B   ; SP0-SP3
PAL_SELECT_SCREEN_MATCH
            db    $30,$00,$12,$16,$27,$36,$0C,$1C,$2C,$12,$1C,$2C   ; BG0-BG3
            db    $FF,$27,$07,$FF,$27,$07,$FF,$27,$07,$FF,$27,$30   ; SP0-SP3
PAL_OVERWORLD_MATCH
            db    $30,$00,$12,$16,$27,$36,$1A,$37,$12,$17,$37,$12   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_CAVE_MATCH
            db    $30,$00,$12,$16,$27,$36,$30,$00,$12,$07,$0F,$17   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON1_MATCH
            db    $30,$00,$12,$16,$27,$36,$0C,$1C,$2C,$12,$1C,$2C   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON2_MATCH
            db    $30,$00,$12,$16,$27,$36,$02,$12,$22,$16,$12,$22   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON3_MATCH
            db    $30,$00,$12,$16,$27,$36,$0B,$1B,$2B,$16,$1B,$2B   ; BG0-BG3
            db    $FF,$37,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON4_MATCH
            db    $30,$00,$12,$16,$27,$36,$08,$18,$28,$12,$18,$28   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON5_MATCH
            db    $30,$00,$12,$16,$27,$36,$0A,$1A,$2A,$16,$1A,$2A   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON6_MATCH
            db    $30,$00,$12,$16,$27,$36,$08,$18,$28,$16,$18,$28   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON7_MATCH
            db    $30,$00,$12,$16,$27,$36,$0A,$1A,$2A,$12,$1A,$2A   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON8_MATCH
            db    $30,$00,$12,$16,$27,$36,$00,$10,$30,$22,$10,$30   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON9_MATCH
            db    $30,$00,$12,$16,$27,$36,$00,$10,$30,$16,$10,$30   ; BG0-BG3
            db    $FF,$27,$17,$02,$22,$30,$16,$27,$30,$FF,$FF,$FF   ; SP0-SP3

; id -> the ids of the palettes that can follow it (transitions), 0-terminated
PAL_SUCC
            dw    PAL_NONE_SUCC
            dw    PAL_TITLE_SCREEN_SUCC
            dw    PAL_INTRO_SUCC
            dw    PAL_SELECT_SCREEN_SUCC
            dw    PAL_OVERWORLD_SUCC
            dw    PAL_CAVE_SUCC
            dw    PAL_DUNGEON1_SUCC
            dw    PAL_DUNGEON2_SUCC
            dw    PAL_DUNGEON3_SUCC
            dw    PAL_DUNGEON4_SUCC
            dw    PAL_DUNGEON5_SUCC
            dw    PAL_DUNGEON6_SUCC
            dw    PAL_DUNGEON7_SUCC
            dw    PAL_DUNGEON8_SUCC
            dw    PAL_DUNGEON9_SUCC
PAL_NONE_SUCC
            dw    0
PAL_TITLE_SCREEN_SUCC
            dw    PAL_INTRO,PAL_SELECT_SCREEN,0
PAL_INTRO_SUCC
            dw    PAL_TITLE_SCREEN,PAL_SELECT_SCREEN,0
PAL_SELECT_SCREEN_SUCC
            dw    PAL_OVERWORLD,0
PAL_OVERWORLD_SUCC
            dw    PAL_CAVE,PAL_DUNGEON1,PAL_DUNGEON2,PAL_DUNGEON3,PAL_DUNGEON4,PAL_DUNGEON5,PAL_DUNGEON6,PAL_DUNGEON7,PAL_DUNGEON8,PAL_DUNGEON9,PAL_SELECT_SCREEN,0
PAL_CAVE_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON1_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON2_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON3_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON4_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON5_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON6_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON7_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON8_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON9_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0

; id -> swizzle tables (PALDATA segment, palettes.s)
PAL_SWIZZLE_LO
            dw    0
            dw    PAL_TITLE_SCREEN_SWIZZLE
            dw    PAL_INTRO_SWIZZLE
            dw    PAL_SELECT_SCREEN_SWIZZLE
            dw    PAL_OVERWORLD_SWIZZLE
            dw    PAL_CAVE_SWIZZLE
            dw    PAL_DUNGEON1_SWIZZLE
            dw    PAL_DUNGEON2_SWIZZLE
            dw    PAL_DUNGEON3_SWIZZLE
            dw    PAL_DUNGEON4_SWIZZLE
            dw    PAL_DUNGEON5_SWIZZLE
            dw    PAL_DUNGEON6_SWIZZLE
            dw    PAL_DUNGEON7_SWIZZLE
            dw    PAL_DUNGEON8_SWIZZLE
            dw    PAL_DUNGEON9_SWIZZLE
PAL_SWIZZLE_HI
            dw    0
            dw    ^PAL_TITLE_SCREEN_SWIZZLE
            dw    ^PAL_INTRO_SWIZZLE
            dw    ^PAL_SELECT_SCREEN_SWIZZLE
            dw    ^PAL_OVERWORLD_SWIZZLE
            dw    ^PAL_CAVE_SWIZZLE
            dw    ^PAL_DUNGEON1_SWIZZLE
            dw    ^PAL_DUNGEON2_SWIZZLE
            dw    ^PAL_DUNGEON3_SWIZZLE
            dw    ^PAL_DUNGEON4_SWIZZLE
            dw    ^PAL_DUNGEON5_SWIZZLE
            dw    ^PAL_DUNGEON6_SWIZZLE
            dw    ^PAL_DUNGEON7_SWIZZLE
            dw    ^PAL_DUNGEON8_SWIZZLE
            dw    ^PAL_DUNGEON9_SWIZZLE

; id -> slot map: for each NES palette RAM entry, the IIgs slot * 2, or $FF if it isn't loaded
; (color 0, which the game writes straight to slot 0, colors that share slot 0 with it, and
; approximated colors, which are shown in another color's slot)
PAL_CELLS
            dw    0
            dw    PAL_TITLE_SCREEN_CELLS
            dw    PAL_INTRO_CELLS
            dw    PAL_SELECT_SCREEN_CELLS
            dw    PAL_OVERWORLD_CELLS
            dw    PAL_CAVE_CELLS
            dw    PAL_DUNGEON1_CELLS
            dw    PAL_DUNGEON2_CELLS
            dw    PAL_DUNGEON3_CELLS
            dw    PAL_DUNGEON4_CELLS
            dw    PAL_DUNGEON5_CELLS
            dw    PAL_DUNGEON6_CELLS
            dw    PAL_DUNGEON7_CELLS
            dw    PAL_DUNGEON8_CELLS
            dw    PAL_DUNGEON9_CELLS
PAL_TITLE_SCREEN_CELLS
            db    $FF,$0C,$02,$04,$FF,$08,$0A,$0C,$FF,$0E,$14,$16,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$06,$10,$18,$FF,$08,$1A,$0C,$FF,$0E,$14,$16,$FF,$06,$10,$12   ; SP0-SP3
PAL_INTRO_CELLS
            db    $FF,$0A,$0A,$0A,$FF,$08,$0A,$0C,$FF,$02,$0A,$0A,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$06,$04,$0E,$FF,$14,$16,$0A,$FF,$02,$18,$0A,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_SELECT_SCREEN_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$16,$FF,$18,$0A,$16,$FF,$1A,$0A,$16,$FF,$1C,$0A,$02   ; SP0-SP3
PAL_OVERWORLD_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$06,$FF,$1A,$10,$06   ; BG0-BG3
            db    $FF,$14,$0A,$1A,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$12,$1C,$1E   ; SP0-SP3
PAL_CAVE_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$02,$04,$06,$FF,$0E,$FF,$1A   ; BG0-BG3
            db    $FF,$14,$0A,$1A,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$10,$12,$1C   ; SP0-SP3
PAL_DUNGEON1_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON2_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$16,$06,$18,$FF,$08,$06,$18   ; BG0-BG3
            db    $FF,$14,$0A,$1A,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$0E,$10,$12   ; SP0-SP3
PAL_DUNGEON3_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$FF,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON4_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON5_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON6_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON7_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$06,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON8_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$04,$0E,$02,$FF,$18,$0E,$02   ; BG0-BG3
            db    $FF,$14,$0A,$1A,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$10,$12,$1C   ; SP0-SP3
PAL_DUNGEON9_CELLS
            db    $FF,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$04,$0E,$02,$FF,$08,$0E,$02   ; BG0-BG3
            db    $FF,$14,$0A,$1A,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$10,$12,$1C   ; SP0-SP3

; from id -> its row of to id -> background groups to redraw (bit 0 = BG0 .. bit 3 = BG3).
; From no palette (0), everything is redrawn.
BG_UPDATE_MASKS
            dw    BG_UPDATE_MASKS_NONE
            dw    BG_UPDATE_MASKS_TITLE_SCREEN
            dw    BG_UPDATE_MASKS_INTRO
            dw    BG_UPDATE_MASKS_SELECT_SCREEN
            dw    BG_UPDATE_MASKS_OVERWORLD
            dw    BG_UPDATE_MASKS_CAVE
            dw    BG_UPDATE_MASKS_DUNGEON1
            dw    BG_UPDATE_MASKS_DUNGEON2
            dw    BG_UPDATE_MASKS_DUNGEON3
            dw    BG_UPDATE_MASKS_DUNGEON4
            dw    BG_UPDATE_MASKS_DUNGEON5
            dw    BG_UPDATE_MASKS_DUNGEON6
            dw    BG_UPDATE_MASKS_DUNGEON7
            dw    BG_UPDATE_MASKS_DUNGEON8
            dw    BG_UPDATE_MASKS_DUNGEON9
BG_UPDATE_MASKS_NONE
            dw    $0000,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111
BG_UPDATE_MASKS_TITLE_SCREEN
            dw    $0000
            dw    %0000   ; to title_screen
            dw    %0101   ; to intro
            dw    %0101   ; to select_screen
            dw    %1101   ; to overworld
            dw    %1101   ; to cave
            dw    %0101   ; to dungeon1
            dw    %1101   ; to dungeon2
            dw    %1101   ; to dungeon3
            dw    %0101   ; to dungeon4
            dw    %1101   ; to dungeon5
            dw    %1101   ; to dungeon6
            dw    %0101   ; to dungeon7
            dw    %1101   ; to dungeon8
            dw    %1101   ; to dungeon9
BG_UPDATE_MASKS_INTRO
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0000   ; to intro
            dw    %0101   ; to select_screen
            dw    %1101   ; to overworld
            dw    %1101   ; to cave
            dw    %0101   ; to dungeon1
            dw    %1101   ; to dungeon2
            dw    %1101   ; to dungeon3
            dw    %0101   ; to dungeon4
            dw    %1101   ; to dungeon5
            dw    %1101   ; to dungeon6
            dw    %0101   ; to dungeon7
            dw    %1101   ; to dungeon8
            dw    %1101   ; to dungeon9
BG_UPDATE_MASKS_SELECT_SCREEN
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %0000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_OVERWORLD
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1100   ; to select_screen
            dw    %0000   ; to overworld
            dw    %1100   ; to cave
            dw    %1100   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %1100   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %1100   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_CAVE
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1100   ; to select_screen
            dw    %1100   ; to overworld
            dw    %0000   ; to cave
            dw    %1100   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %1100   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %1100   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON1
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %0000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON2
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1100   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1100   ; to dungeon1
            dw    %0000   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %1100   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %1100   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON3
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1000   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON4
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %0000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON5
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1000   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON6
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1000   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON7
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %0000   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %1100   ; to dungeon8
            dw    %1100   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON8
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1100   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1100   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %1100   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %1100   ; to dungeon7
            dw    %0000   ; to dungeon8
            dw    %1000   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON9
            dw    $0000
            dw    %1101   ; to title_screen
            dw    %1101   ; to intro
            dw    %1100   ; to select_screen
            dw    %1100   ; to overworld
            dw    %1100   ; to cave
            dw    %1100   ; to dungeon1
            dw    %1100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %1100   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %1100   ; to dungeon7
            dw    %1000   ; to dungeon8
            dw    %0000   ; to dungeon9
