; Auto-generated by scripts/generate-palette-transitions.js from src/games/zelda/palettes/.
; Do not edit by hand -- regenerate instead.
;
; Every palette has one fixed IIgs slot layout: the IIgs palette 0 slot that each of the 32 NES
; palette RAM entries ($3F00-$3F1F) is shown in.  The layouts are chosen together, so that the
; background groups that keep the same slots across the transitions don't need their tiles
; redrawn (a group whose slots change has to be recompiled with the new swizzle table).
;
; Requires: NES_ColorToIIgs_X, NES_SetPaletteMap, RefreshPPUAttributes, PPU_MEM, SHR_PALETTES

; Swizzle tables, in the PALDATA segment (palettes.s)
PAL_TITLE_SCREEN_SWIZZLE EXT
PAL_INTRO_SWIZZLE EXT
PAL_SELECT_SCREEN_SWIZZLE EXT
PAL_OVERWORLD_SWIZZLE EXT
PAL_CAVE_SWIZZLE EXT
PAL_DUNGEON1_SWIZZLE EXT
PAL_DUNGEON2_SWIZZLE EXT
PAL_DUNGEON3_SWIZZLE EXT
PAL_DUNGEON4_SWIZZLE EXT
PAL_DUNGEON5_SWIZZLE EXT
PAL_DUNGEON6_SWIZZLE EXT
PAL_DUNGEON7_SWIZZLE EXT
PAL_DUNGEON8_SWIZZLE EXT
PAL_DUNGEON9_SWIZZLE EXT

; Palette ids, word-aligned so they index the tables below directly.  0 = no palette.
PAL_TITLE_SCREEN equ 2
PAL_INTRO equ 4
PAL_SELECT_SCREEN equ 6
PAL_OVERWORLD equ 8
PAL_CAVE equ 10
PAL_DUNGEON1 equ 12
PAL_DUNGEON2 equ 14
PAL_DUNGEON3 equ 16
PAL_DUNGEON4 equ 18
PAL_DUNGEON5 equ 20
PAL_DUNGEON6 equ 22
PAL_DUNGEON7 equ 24
PAL_DUNGEON8 equ 26
PAL_DUNGEON9 equ 28

; Layouts (NES color -> [slots] per group; *reserved, ~shown as):
;   title_screen
;     BG0 $36 $0F $00 $10 -> [0,1,2,3]
;     BG1 $36 $17 *$07 $0F -> [0,4,5,6]
;     BG2 $36 $08 $1A $28 -> [0,7,11,12]
;     BG3 $36 $30 $3B $22 -> [0,10,8,9]
;     SP0 $36 $30 $3B $16 -> [0,10,8,13]
;     SP1 $36 $17 $27 $0F -> [0,4,14,1]
;     SP2 $36 $08 $1A $28 -> [0,7,11,12]
;     SP3 $36 $30 $3B $22 -> [0,10,8,9]
;   intro
;     BG0 $0F $30 $30 $30 -> [0,5,5,5]
;     BG1 $0F $21 $30 $30 -> [0,4,5,6]
;     BG2 $0F $16 $30 $30 -> [0,1,5,5]
;     BG3 $0F $29 $1A $09 -> [0,10,8,9]
;     SP0 $0F $29 $37 $17 -> [0,10,2,3]
;     SP1 $0F $02 $22 $30 -> [0,7,11,5]
;     SP2 $0F $16 $27 $30 -> [0,1,12,5]
;     SP3 $0F $0B $1B $2B -> [0,13,14,15]
;   select_screen
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0C $1C $2C -> [0,7,8,9]
;     BG3 $0F $12 $1C $2C -> [0,10,8,9]
;     SP0 $0F *$29 $27 $07 -> [0,11,5,12]
;     SP1 $0F *$29 $27 $07 -> [0,13,5,12]
;     SP2 $0F *$29 $27 $07 -> [0,14,5,12]
;     SP3 $0F *$15 $27 $30 -> [0,15,5,1]
;   overworld
;     BG0 $0F $30 $00 $12 -> [0,1,2,9]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $1A $37 $12 -> [0,7,8,9]
;     BG3 $0F $17 $37 $12 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17 -> [0,3,5,10]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$1C *$16 -> [0,13,14,15]
;   cave
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $30 $00 $12 -> [0,1,2,3]
;     BG3 $0F $07 $0F $17 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17 -> [0,7,5,9]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$1C *$16 -> [0,13,14,15]
;   dungeon1
;     BG0 $0F $30 $00 $12 -> [0,1,2,10]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0C $1C $2C -> [0,7,8,9]
;     BG3 $0F $12 $1C $2C -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,3,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0C *$1C *$2C -> [0,13,14,15]
;   dungeon2
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $02 $12 $22 -> [0,7,8,9]
;     BG3 $0F $16 $12 $22 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17 -> [0,11,5,12]
;     SP1 $0F $02 $22 $30 -> [0,7,9,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$02 *$12 *$22 -> [0,13,14,15]
;   dungeon3
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0B $1B $2B -> [0,7,8,9]
;     BG3 $0F $16 $1B $2B -> [0,4,8,9]
;     SP0 $0F *$29 $37~$36 $17~$16 -> [0,10,6,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0B *$1B *$2B -> [0,13,14,15]
;   dungeon4
;     BG0 $0F $30 $00 $12 -> [0,1,2,10]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $08 $18 $28 -> [0,7,8,9]
;     BG3 $0F $12 $18 $28 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,3,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0F *$18 *$28 -> [0,13,14,15]
;   dungeon5
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0A $1A $2A -> [0,7,8,9]
;     BG3 $0F $16 $1A $2A -> [0,4,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0A *$1A *$2A -> [0,13,14,15]
;   dungeon6
;     BG0 $0F $30 $00 $12 -> [0,1,2,3]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $08 $18 $28 -> [0,7,8,9]
;     BG3 $0F $16 $18 $28 -> [0,4,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,10,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$08 *$18 *$28 -> [0,13,14,15]
;   dungeon7
;     BG0 $0F $30 $00 $12 -> [0,1,2,10]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $0A $1A $2A -> [0,7,8,9]
;     BG3 $0F $12 $1A $2A -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17~$16 -> [0,3,5,4]
;     SP1 $0F $02 $22 $30 -> [0,11,12,1]
;     SP2 $0F $16 $27 $30 -> [0,4,5,1]
;     SP3 $0F *$0A *$1A *$2A -> [0,13,14,15]
;   dungeon8
;     BG0 $0F $30 $00 $12 -> [0,9,7,1]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $00 $10 $30 -> [0,7,8,9]
;     BG3 $0F $22 $10 $30 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17 -> [0,2,5,3]
;     SP1 $0F $02 $22 $30 -> [0,11,10,9]
;     SP2 $0F $16 $27 $30 -> [0,4,5,9]
;     SP3 $0F *$00 *$10 *$30 -> [0,12,13,14]
;   dungeon9
;     BG0 $0F $30 $00 $12 -> [0,9,7,1]
;     BG1 $0F $16 $27 $36 -> [0,4,5,6]
;     BG2 $0F $00 $10 $30 -> [0,7,8,9]
;     BG3 $0F $16 $10 $30 -> [0,10,8,9]
;     SP0 $0F *$29 $27 $17 -> [0,2,5,3]
;     SP1 $0F $02 $22 $30 -> [0,11,12,9]
;     SP2 $0F $16 $27 $30 -> [0,4,5,9]
;     SP3 $0F *$0F *$10 *$30 -> [0,13,14,15]

            mx    %00

; UpdatePalette
;
; X = from palette id (PAL_*, or 0 for none), Y = to palette id
;
; Switches the swizzle tables to the new palette, loads its colors into IIgs palette 0 from the
; current NES palette RAM (so colors the game changes on the fly are kept), then redraws the
; background groups whose slots changed.  Call from the GS task (it redraws tiles).
UpdatePalette
            lda   BG_UPDATE_MASKS,x
            pha
            lda   (1,s),y
            sta   1,s                 ; 1,s = groups to redraw

            phy
            ldx   PAL_SWIZZLE_LO,y
            lda   PAL_SWIZZLE_HI,y
            jsr   NES_SetPaletteMap
            ply

            lda   PAL_CELLS,y
            pha                       ; 1,s = slot map, 3,s = groups to redraw
            ldy   #31                 ; Backwards, so the BG colors win a shared slot and $3F00 is last
:loop       lda   (1,s),y
            and   #$00FF
            cmp   #$00FF
            beq   :next               ; not shown
            pha                       ; 1,s = slot * 2
            tyx
            ldal  PPU_MEM+$3F00,x
            jsr   NES_ColorToIIgs_X
            plx
            stal  SHR_PALETTES,x
:next       dey
            bpl   :loop
            pla
            pla
            jmp   RefreshPPUAttributes

; SetPaletteColor
;
; A = NES color, Y = NES palette RAM offset (0-31), X = palette id.  Shows one changed color in
; palette X's layout.  Colors that aren't shown are ignored.
SetPaletteColor
            pha
            lda   PAL_CELLS,x
            pha                       ; 1,s = slot map, 3,s = color
            lda   (1,s),y
            and   #$00FF
            cmp   #$00FF
            beq   :skip
            sta   1,s                 ; 1,s = slot * 2
            lda   3,s
            jsr   NES_ColorToIIgs_X
            plx
            stal  SHR_PALETTES,x
            pla
            rts
:skip       pla
            pla
            rts

; DetectNESPalette
;
; X = the current palette id (0 = none).  Returns A = Y = the PAL_* id of the palette whose
; colors are all in palette RAM ($3F00-$3F1F, other than the reserved ones and the unused
; color 0s), or 0 if there is none (e.g. a step of a fade).  The current palette is tried first,
; then the palettes that follow it in the transitions, then the rest.
DetectNESPalette
            php
            rep   #$30
            stx   :from
            txa
            beq   :all
            jsr   :match              ; still the current palette?
            bcs   :found
            ldx   :from
            lda   PAL_SUCC,x          ; its successors, a 0-terminated list of ids
:snext      sta   :ptr
            tax
            lda:  0,x
            beq   :all
            tax
            jsr   :match
            bcs   :found
            lda   :ptr
            inc
            inc
            bra   :snext
:all        ldx   #2
:anext      jsr   :match
            bcs   :found
            inx
            inx
            cpx   #30
            bcc   :anext
            ldx   #0
:found      txy
            plp
            tya
            rts

; X = palette id.  Carry set if its colors are in palette RAM.  X is kept.
:match      phx
            lda   PAL_MATCH,x
            clc
            adc   #31
            tay                       ; Y -> the palette's bytes, from the last
            ldx   #31                 ; X = palette RAM offset
            sep   #$20
            mx    %10
:mbyte      lda:  0,y
            cmp   #$FF                ; any value
            beq   :mnext
            cmpl  PPU_MEM+$3F00,x
            bne   :mfail
:mnext      dey
            dex
            bpl   :mbyte
            rep   #$20
            mx    %00
            plx
            sec
            rts
:mfail      rep   #$20
            plx
            clc
            rts

:from       ds    2
:ptr        ds    2

; id -> palette RAM bytes to match ($3F00-$3F1F; $FF = any value: not shown, or reserved)
PAL_MATCH
            dw    0
            dw    PAL_TITLE_SCREEN_MATCH
            dw    PAL_INTRO_MATCH
            dw    PAL_SELECT_SCREEN_MATCH
            dw    PAL_OVERWORLD_MATCH
            dw    PAL_CAVE_MATCH
            dw    PAL_DUNGEON1_MATCH
            dw    PAL_DUNGEON2_MATCH
            dw    PAL_DUNGEON3_MATCH
            dw    PAL_DUNGEON4_MATCH
            dw    PAL_DUNGEON5_MATCH
            dw    PAL_DUNGEON6_MATCH
            dw    PAL_DUNGEON7_MATCH
            dw    PAL_DUNGEON8_MATCH
            dw    PAL_DUNGEON9_MATCH
PAL_TITLE_SCREEN_MATCH
            db    $36,$0F,$00,$10,$FF,$17,$FF,$0F,$FF,$08,$1A,$28,$FF,$30,$3B,$22   ; BG0-BG3
            db    $FF,$30,$3B,$16,$FF,$17,$27,$0F,$FF,$08,$1A,$28,$FF,$30,$3B,$22   ; SP0-SP3
PAL_INTRO_MATCH
            db    $0F,$30,$30,$30,$FF,$21,$30,$30,$FF,$16,$30,$30,$FF,$29,$1A,$09   ; BG0-BG3
            db    $FF,$29,$37,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$0B,$1B,$2B   ; SP0-SP3
PAL_SELECT_SCREEN_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$0C,$1C,$2C,$FF,$12,$1C,$2C   ; BG0-BG3
            db    $FF,$FF,$27,$07,$FF,$FF,$27,$07,$FF,$FF,$27,$07,$FF,$FF,$27,$30   ; SP0-SP3
PAL_OVERWORLD_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$1A,$37,$12,$FF,$17,$37,$12   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_CAVE_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$30,$00,$12,$FF,$07,$0F,$17   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON1_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$0C,$1C,$2C,$FF,$12,$1C,$2C   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON2_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$02,$12,$22,$FF,$16,$12,$22   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON3_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$0B,$1B,$2B,$FF,$16,$1B,$2B   ; BG0-BG3
            db    $FF,$FF,$37,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON4_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$08,$18,$28,$FF,$12,$18,$28   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON5_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$0A,$1A,$2A,$FF,$16,$1A,$2A   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON6_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$08,$18,$28,$FF,$16,$18,$28   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON7_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$0A,$1A,$2A,$FF,$12,$1A,$2A   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON8_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$00,$10,$30,$FF,$22,$10,$30   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3
PAL_DUNGEON9_MATCH
            db    $0F,$30,$00,$12,$FF,$16,$27,$36,$FF,$00,$10,$30,$FF,$16,$10,$30   ; BG0-BG3
            db    $FF,$FF,$27,$17,$FF,$02,$22,$30,$FF,$16,$27,$30,$FF,$FF,$FF,$FF   ; SP0-SP3

; id -> the ids of the palettes that can follow it (transitions), 0-terminated
PAL_SUCC
            dw    PAL_NONE_SUCC
            dw    PAL_TITLE_SCREEN_SUCC
            dw    PAL_INTRO_SUCC
            dw    PAL_SELECT_SCREEN_SUCC
            dw    PAL_OVERWORLD_SUCC
            dw    PAL_CAVE_SUCC
            dw    PAL_DUNGEON1_SUCC
            dw    PAL_DUNGEON2_SUCC
            dw    PAL_DUNGEON3_SUCC
            dw    PAL_DUNGEON4_SUCC
            dw    PAL_DUNGEON5_SUCC
            dw    PAL_DUNGEON6_SUCC
            dw    PAL_DUNGEON7_SUCC
            dw    PAL_DUNGEON8_SUCC
            dw    PAL_DUNGEON9_SUCC
PAL_NONE_SUCC
            dw    0
PAL_TITLE_SCREEN_SUCC
            dw    PAL_INTRO,PAL_SELECT_SCREEN,0
PAL_INTRO_SUCC
            dw    PAL_TITLE_SCREEN,PAL_SELECT_SCREEN,0
PAL_SELECT_SCREEN_SUCC
            dw    PAL_OVERWORLD,0
PAL_OVERWORLD_SUCC
            dw    PAL_CAVE,PAL_DUNGEON1,PAL_DUNGEON2,PAL_DUNGEON3,PAL_DUNGEON4,PAL_DUNGEON5,PAL_DUNGEON6,PAL_DUNGEON7,PAL_DUNGEON8,PAL_DUNGEON9,PAL_SELECT_SCREEN,0
PAL_CAVE_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON1_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON2_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON3_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON4_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON5_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON6_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON7_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON8_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0
PAL_DUNGEON9_SUCC
            dw    PAL_OVERWORLD,PAL_SELECT_SCREEN,0

; id -> swizzle tables (PALDATA segment, palettes.s)
PAL_SWIZZLE_LO
            dw    0
            dw    PAL_TITLE_SCREEN_SWIZZLE
            dw    PAL_INTRO_SWIZZLE
            dw    PAL_SELECT_SCREEN_SWIZZLE
            dw    PAL_OVERWORLD_SWIZZLE
            dw    PAL_CAVE_SWIZZLE
            dw    PAL_DUNGEON1_SWIZZLE
            dw    PAL_DUNGEON2_SWIZZLE
            dw    PAL_DUNGEON3_SWIZZLE
            dw    PAL_DUNGEON4_SWIZZLE
            dw    PAL_DUNGEON5_SWIZZLE
            dw    PAL_DUNGEON6_SWIZZLE
            dw    PAL_DUNGEON7_SWIZZLE
            dw    PAL_DUNGEON8_SWIZZLE
            dw    PAL_DUNGEON9_SWIZZLE
PAL_SWIZZLE_HI
            dw    0
            dw    ^PAL_TITLE_SCREEN_SWIZZLE
            dw    ^PAL_INTRO_SWIZZLE
            dw    ^PAL_SELECT_SCREEN_SWIZZLE
            dw    ^PAL_OVERWORLD_SWIZZLE
            dw    ^PAL_CAVE_SWIZZLE
            dw    ^PAL_DUNGEON1_SWIZZLE
            dw    ^PAL_DUNGEON2_SWIZZLE
            dw    ^PAL_DUNGEON3_SWIZZLE
            dw    ^PAL_DUNGEON4_SWIZZLE
            dw    ^PAL_DUNGEON5_SWIZZLE
            dw    ^PAL_DUNGEON6_SWIZZLE
            dw    ^PAL_DUNGEON7_SWIZZLE
            dw    ^PAL_DUNGEON8_SWIZZLE
            dw    ^PAL_DUNGEON9_SWIZZLE

; id -> slot map: for each NES palette RAM entry, the IIgs slot * 2, or $FF if it isn't shown
; (color 0 of the groups other than BG0, colors that share slot 0 with $3F00, and approximated
; colors, which are shown in another color's slot)
PAL_CELLS
            dw    0
            dw    PAL_TITLE_SCREEN_CELLS
            dw    PAL_INTRO_CELLS
            dw    PAL_SELECT_SCREEN_CELLS
            dw    PAL_OVERWORLD_CELLS
            dw    PAL_CAVE_CELLS
            dw    PAL_DUNGEON1_CELLS
            dw    PAL_DUNGEON2_CELLS
            dw    PAL_DUNGEON3_CELLS
            dw    PAL_DUNGEON4_CELLS
            dw    PAL_DUNGEON5_CELLS
            dw    PAL_DUNGEON6_CELLS
            dw    PAL_DUNGEON7_CELLS
            dw    PAL_DUNGEON8_CELLS
            dw    PAL_DUNGEON9_CELLS
PAL_TITLE_SCREEN_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$16,$18,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$14,$10,$1A,$FF,$08,$1C,$02,$FF,$0E,$16,$18,$FF,$14,$10,$12   ; SP0-SP3
PAL_INTRO_CELLS
            db    $00,$0A,$0A,$0A,$FF,$08,$0A,$0C,$FF,$02,$0A,$0A,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$14,$04,$06,$FF,$0E,$16,$0A,$FF,$02,$18,$0A,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_SELECT_SCREEN_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$16,$0A,$18,$FF,$1A,$0A,$18,$FF,$1C,$0A,$18,$FF,$1E,$0A,$02   ; SP0-SP3
PAL_OVERWORLD_CELLS
            db    $00,$02,$04,$12,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$06,$0A,$14,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_CAVE_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$02,$04,$06,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$0E,$0A,$12,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON1_CELLS
            db    $00,$02,$04,$14,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$06,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON2_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$16,$0A,$18,$FF,$0E,$12,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON3_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$FF,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON4_CELLS
            db    $00,$02,$04,$14,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$06,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON5_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON6_CELLS
            db    $00,$02,$04,$06,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$08,$10,$12   ; BG0-BG3
            db    $FF,$14,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON7_CELLS
            db    $00,$02,$04,$14,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$06,$0A,$FF,$FF,$16,$18,$02,$FF,$08,$0A,$02,$FF,$1A,$1C,$1E   ; SP0-SP3
PAL_DUNGEON8_CELLS
            db    $00,$12,$0E,$02,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$04,$0A,$06,$FF,$16,$14,$12,$FF,$08,$0A,$12,$FF,$18,$1A,$1C   ; SP0-SP3
PAL_DUNGEON9_CELLS
            db    $00,$12,$0E,$02,$FF,$08,$0A,$0C,$FF,$0E,$10,$12,$FF,$14,$10,$12   ; BG0-BG3
            db    $FF,$04,$0A,$06,$FF,$16,$18,$12,$FF,$08,$0A,$12,$FF,$1A,$1C,$1E   ; SP0-SP3

; from id -> its row of to id -> background groups to redraw (bit 0 = BG0 .. bit 3 = BG3).
; From no palette (0), everything is redrawn.
BG_UPDATE_MASKS
            dw    BG_UPDATE_MASKS_NONE
            dw    BG_UPDATE_MASKS_TITLE_SCREEN
            dw    BG_UPDATE_MASKS_INTRO
            dw    BG_UPDATE_MASKS_SELECT_SCREEN
            dw    BG_UPDATE_MASKS_OVERWORLD
            dw    BG_UPDATE_MASKS_CAVE
            dw    BG_UPDATE_MASKS_DUNGEON1
            dw    BG_UPDATE_MASKS_DUNGEON2
            dw    BG_UPDATE_MASKS_DUNGEON3
            dw    BG_UPDATE_MASKS_DUNGEON4
            dw    BG_UPDATE_MASKS_DUNGEON5
            dw    BG_UPDATE_MASKS_DUNGEON6
            dw    BG_UPDATE_MASKS_DUNGEON7
            dw    BG_UPDATE_MASKS_DUNGEON8
            dw    BG_UPDATE_MASKS_DUNGEON9
BG_UPDATE_MASKS_NONE
            dw    $0000,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111,%1111
BG_UPDATE_MASKS_TITLE_SCREEN
            dw    $0000
            dw    %0000   ; to title_screen
            dw    %0101   ; to intro
            dw    %0100   ; to select_screen
            dw    %0101   ; to overworld
            dw    %0100   ; to cave
            dw    %0101   ; to dungeon1
            dw    %0100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %0101   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %0101   ; to dungeon7
            dw    %0101   ; to dungeon8
            dw    %0101   ; to dungeon9
BG_UPDATE_MASKS_INTRO
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0000   ; to intro
            dw    %0101   ; to select_screen
            dw    %0101   ; to overworld
            dw    %0101   ; to cave
            dw    %0101   ; to dungeon1
            dw    %0101   ; to dungeon2
            dw    %1101   ; to dungeon3
            dw    %0101   ; to dungeon4
            dw    %1101   ; to dungeon5
            dw    %1101   ; to dungeon6
            dw    %0101   ; to dungeon7
            dw    %0101   ; to dungeon8
            dw    %0101   ; to dungeon9
BG_UPDATE_MASKS_SELECT_SCREEN
            dw    $0000
            dw    %0100   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0100   ; to cave
            dw    %0001   ; to dungeon1
            dw    %0000   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0001   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0001   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_OVERWORLD
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0000   ; to overworld
            dw    %0101   ; to cave
            dw    %0001   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0001   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0001   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_CAVE
            dw    $0000
            dw    %0100   ; to title_screen
            dw    %0101   ; to intro
            dw    %0100   ; to select_screen
            dw    %0101   ; to overworld
            dw    %0000   ; to cave
            dw    %0101   ; to dungeon1
            dw    %0100   ; to dungeon2
            dw    %1100   ; to dungeon3
            dw    %0101   ; to dungeon4
            dw    %1100   ; to dungeon5
            dw    %1100   ; to dungeon6
            dw    %0101   ; to dungeon7
            dw    %0101   ; to dungeon8
            dw    %0101   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON1
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0101   ; to cave
            dw    %0000   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON2
            dw    $0000
            dw    %0100   ; to title_screen
            dw    %0101   ; to intro
            dw    %0000   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0100   ; to cave
            dw    %0001   ; to dungeon1
            dw    %0000   ; to dungeon2
            dw    %1000   ; to dungeon3
            dw    %0001   ; to dungeon4
            dw    %1000   ; to dungeon5
            dw    %1000   ; to dungeon6
            dw    %0001   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON3
            dw    $0000
            dw    %1100   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1001   ; to overworld
            dw    %1100   ; to cave
            dw    %1001   ; to dungeon1
            dw    %1000   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1001   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1001   ; to dungeon7
            dw    %1001   ; to dungeon8
            dw    %1001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON4
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0101   ; to cave
            dw    %0000   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON5
            dw    $0000
            dw    %1100   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1001   ; to overworld
            dw    %1100   ; to cave
            dw    %1001   ; to dungeon1
            dw    %1000   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1001   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1001   ; to dungeon7
            dw    %1001   ; to dungeon8
            dw    %1001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON6
            dw    $0000
            dw    %1100   ; to title_screen
            dw    %1101   ; to intro
            dw    %1000   ; to select_screen
            dw    %1001   ; to overworld
            dw    %1100   ; to cave
            dw    %1001   ; to dungeon1
            dw    %1000   ; to dungeon2
            dw    %0000   ; to dungeon3
            dw    %1001   ; to dungeon4
            dw    %0000   ; to dungeon5
            dw    %0000   ; to dungeon6
            dw    %1001   ; to dungeon7
            dw    %1001   ; to dungeon8
            dw    %1001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON7
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0101   ; to cave
            dw    %0000   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0000   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0000   ; to dungeon7
            dw    %0001   ; to dungeon8
            dw    %0001   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON8
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0101   ; to cave
            dw    %0001   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0001   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0001   ; to dungeon7
            dw    %0000   ; to dungeon8
            dw    %0000   ; to dungeon9
BG_UPDATE_MASKS_DUNGEON9
            dw    $0000
            dw    %0101   ; to title_screen
            dw    %0101   ; to intro
            dw    %0001   ; to select_screen
            dw    %0001   ; to overworld
            dw    %0101   ; to cave
            dw    %0001   ; to dungeon1
            dw    %0001   ; to dungeon2
            dw    %1001   ; to dungeon3
            dw    %0001   ; to dungeon4
            dw    %1001   ; to dungeon5
            dw    %1001   ; to dungeon6
            dw    %0001   ; to dungeon7
            dw    %0000   ; to dungeon8
            dw    %0000   ; to dungeon9
